export default [
  {
    id: "clear",
    customColor: "#db2121",
    value: "",
    type: "clear",
    buttonLabel: "AC",
  },
  {
    id: "divide",
    value: "/",
    type: "operand",
    customColor: "#828181",
    buttonLabel: "/",
  },
  {
    id: "multiply",
    value: "X",
    type: "operand",
    customColor: "#828181",
    buttonLabel: "X",
  },
  {
    id: "seven",
    value: "7",
    type: "input",
    buttonLabel: "7",
  },
  {
    id: "eight",
    value: "8",
    type: "input",
    buttonLabel: "8",
  },
  {
    id: "nine",
    value: "9",
    type: "input",
    buttonLabel: "9",
  },
  {
    id: "subtract",
    value: "-",
    type: "operand",
    customColor: "#828181",
    buttonLabel: "-",
  },
  {
    id: "four",
    value: "4",
    type: "input",
    buttonLabel: "4",
  },
  {
    id: "five",
    value: "5",
    type: "input",
    buttonLabel: "5",
  },
  {
    id: "six",
    value: "6",
    type: "input",
    buttonLabel: "6",
  },
  {
    id: "add",
    value: "+",
    type: "operand",
    customColor: "#828181",
    buttonLabel: "+",
  },
  {
    id: "one",
    value: "1",
    type: "input",
    buttonLabel: "1",
  },
  {
    id: "two",
    value: "2",
    type: "input",
    buttonLabel: "2",
  },
  {
    id: "three",
    value: "3",
    type: "input",
    buttonLabel: "3",
  },
  {
    id: "equals",
    customColor: "#2469c9",
    value: "=",
    type: "equals",
    buttonLabel: "=",
  },
  {
    id: "zero",
    value: "0",
    type: "zero",
    buttonLabel: "0",
  },

  {
    id: "decimal",
    value: ".",
    type: "input",
    buttonLabel: ".",
  },
];
