export default [
  {
    id: "equals",
    display: "=",
    type: "operand",
    buttonLabel: "=",
  },
  {
    id: "zero",
    display: "0",
    type: "input",
    buttonLabel: "0",
  },
  {
    id: "one",
    display: "1",
    type: "input",
    buttonLabel: "1",
  },
  {
    id: "two",
    display: "2",
    type: "input",
    buttonLabel: "2",
  },
  {
    id: "three",
    display: "3",
    type: "input",
    buttonLabel: "3",
  },
  {
    id: "four",
    display: "4",
    type: "input",
    buttonLabel: "4",
  },
  {
    id: "five",
    display: "5",
    type: "input",
    buttonLabel: "5",
  },
  {
    id: "six",
    display: "6",
    type: "input",
    buttonLabel: "6",
  },
  {
    id: "seven",
    display: "7",
    type: "input",
    buttonLabel: "7",
  },
  {
    id: "eight",
    display: "8",
    type: "input",
    buttonLabel: "8",
  },
  {
    id: "nine",
    display: "9",
    type: "input",
    buttonLabel: "9",
  },
  {
    id: "add",
    display: "+",
    type: "operand",
    buttonLabel: "+",
  },
  {
    id: "subtract",
    display: "-",
    type: "operand",
    buttonLabel: "-",
  },
  {
    id: "multiply",
    display: "X",
    type: "operand",
    buttonLabel: "X",
  },
  {
    id: "divide",
    display: "/",
    type: "operand",
    buttonLabel: "/",
  },
  {
    id: "decimal",
    display: ".",
    type: "input",
    buttonLabel: ".",
  },
  {
    id: "clear",
    display: "",
    type: "input",
    buttonLabel: "AC",
  },
];
